version: '3.8'

services:
  automatech-api:
    image: victor1204s/automatech-api:latest
    networks:
      - traefik-public
    volumes:
      - automatech-sessions:/app/sessions
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.docker.lbswarm=true
        - traefik.constraint-label=traefik-public
        
        # HTTP Router
        - traefik.http.routers.automatech-api.rule=Host(`api.wattsapi.automatech.tech`)
        - traefik.http.routers.automatech-api.entrypoints=web
        - traefik.http.routers.automatech-api.middlewares=https-redirect
        
        # HTTPS Router
        - traefik.http.routers.automatech-api-secure.rule=Host(`api.wattsapi.automatech.tech`)
        - traefik.http.routers.automatech-api-secure.entrypoints=websecure
        - traefik.http.routers.automatech-api-secure.tls=true
        - traefik.http.routers.automatech-api-secure.tls.certresolver=letsencryptresolver
        - traefik.http.routers.automatech-api-secure.service=automatech-api
        
        # Service
        - traefik.http.services.automatech-api.loadbalancer.server.port=3001
        
        # CORS Middleware
        - traefik.http.middlewares.automatech-cors.headers.accesscontrolallowmethods=GET,POST,DELETE,OPTIONS
        - traefik.http.middlewares.automatech-cors.headers.accesscontrolalloworiginlist=*
        - traefik.http.middlewares.automatech-cors.headers.accesscontrolmaxage=100
        - traefik.http.middlewares.automatech-cors.headers.addvaryheader=true

  automatech-dashboard:
    image: victor1204s/automatech-dashboard:latest
    networks:
      - traefik-public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.docker.lbswarm=true
        - traefik.constraint-label=traefik-public
        
        # HTTP Router
        - traefik.http.routers.automatech-dashboard.rule=Host(`wattsapi.automatech.tech`)
        - traefik.http.routers.automatech-dashboard.entrypoints=web
        - traefik.http.routers.automatech-dashboard.middlewares=https-redirect
        
        # HTTPS Router
        - traefik.http.routers.automatech-dashboard-secure.rule=Host(`wattsapi.automatech.tech`)
        - traefik.http.routers.automatech-dashboard-secure.entrypoints=websecure
        - traefik.http.routers.automatech-dashboard-secure.tls=true
        - traefik.http.routers.automatech-dashboard-secure.tls.certresolver=letsencryptresolver
        - traefik.http.routers.automatech-dashboard-secure.service=automatech-dashboard
        
        # Service
        - traefik.http.services.automatech-dashboard.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true

volumes:
  automatech-sessions:
    driver: local
